### ISSUE TITLE
Consider renaming traits to avoid conflict with `io::Read` and `io::Write`

### ISSUE THREAD

**Issue by casey** [That3Percent/tree-buf#14]
Rust code often has `std::io::Read` and/or `std::io::Write` in scope, which might conflict with `tree_buf::Read` and `tree_buff::Write`.

`Load` and `Store` is one possibility that wouldn't conflict.

**Comment by That3Percent** [comment]
Thanks! I will rename these. I haven't yet come across a name that I love (besides maybe `Serialize` and `Deserialize` but `serde` took those). `Load` and `Store` while not wrong just remind too much of databases. If you want to send it over the network, for example, people don't think of it as "loading and storing" data on the wire.

**Comment by casey** [comment]
Names are hard! Another idea is `Encode` and `Decode`.

**Comment by That3Percent** [comment]
`Encode` & `Decode` it is! Implemented in [https://github.com/That3Percent/tree-buf/commit/7dbdfcc7a76f2bf2c34481377c9d031c6612c15c](https://github.com/That3Percent/tree-buf/commit/7dbdfcc7a76f2bf2c34481377c9d031c6612c15c)
